=== r0bertz/gentoo-cn/dtd/book.dtd
<!ENTITY  % inline.class "sup|sub|b|brite|c|e|path|img|br|mail|uri|keyval">
<!ENTITY  % pre.class    "comment|i|keyword|ident|const|stmt|var|keyval">
<!ENTITY  % block.class  "figure|fig|note|impo|warn|pre|p|table|ul|ol|dl">

<!ENTITY half   "&#x00BD;"> <!-- VULGAR FRACTION ONE HALF -->
<!ENTITY frac12 "&#x00BD;"> <!-- VULGAR FRACTION ONE HALF -->
<!ENTITY frac14 "&#x00BC;"> <!-- VULGAR FRACTION ONE QUARTER -->
<!ENTITY frac34 "&#x00BE;"> <!-- VULGAR FRACTION THREE QUARTERS -->
<!ENTITY frac18 "&#x215B;"> <!--  -->
<!ENTITY frac38 "&#x215C;"> <!--  -->
<!ENTITY frac58 "&#x215D;"> <!--  -->
<!ENTITY frac78 "&#x215E;"> <!--  -->
<!ENTITY sup1   "&#x00B9;"> <!-- SUPERSCRIPT ONE -->
<!ENTITY sup2   "&#x00B2;"> <!-- SUPERSCRIPT TWO -->
<!ENTITY sup3   "&#x00B3;"> <!-- SUPERSCRIPT THREE -->
<!ENTITY plus   "&#x002B;"> <!-- PLUS SIGN -->
<!ENTITY plusmn "&#x00B1;"> <!-- PLUS-MINUS SIGN -->
<!ENTITY lt     "&#38;#60;"> <!-- LESS-THAN SIGN -->
<!ENTITY equals "&#x003D;"> <!-- EQUALS SIGN -->
<!ENTITY gt     "&#x003E;"> <!-- GREATER-THAN SIGN -->
<!ENTITY divide "&#x00F7;"> <!-- DIVISION SIGN -->
<!ENTITY times  "&#x00D7;"> <!-- MULTIPLICATION SIGN -->
<!ENTITY curren "&#x00A4;"> <!-- CURRENCY SIGN -->
<!ENTITY pound  "&#x00A3;"> <!-- POUND SIGN -->
<!ENTITY dollar "&#x0024;"> <!-- DOLLAR SIGN -->
<!ENTITY cent   "&#x00A2;"> <!-- CENT SIGN -->
<!ENTITY yen    "&#x00A5;"> <!-- YEN SIGN -->
<!ENTITY num    "&#x0023;"> <!-- NUMBER SIGN -->
<!ENTITY percnt "&#x0025;"> <!-- PERCENT SIGN -->
<!ENTITY amp    "&#38;#38;"> <!-- AMPERSAND -->
<!ENTITY ast    "&#x2217;"> <!-- ASTERISK OPERATOR -->
<!ENTITY commat "&#x0040;"> <!-- COMMERCIAL AT -->
<!ENTITY lsqb   "&#x005B;"> <!-- LEFT SQUARE BRACKET -->
<!ENTITY bsol   "&#x005C;"> <!-- REVERSE SOLIDUS -->
<!ENTITY rsqb   "&#x005D;"> <!-- RIGHT SQUARE BRACKET -->
<!ENTITY lcub   "&#x007B;"> <!-- LEFT CURLY BRACKET -->
<!ENTITY horbar "&#x2015;"> <!-- HORIZONTAL BAR -->
<!ENTITY verbar "&#x007C;"> <!-- VERTICAL LINE -->
<!ENTITY rcub   "&#x007D;"> <!-- RIGHT CURLY BRACKET -->
<!ENTITY micro  "&#x00B5;"> <!-- MICRO SIGN -->
<!ENTITY ohm    "&#x2126;"> <!-- OHM SIGN -->
<!ENTITY deg    "&#x00B0;"> <!-- DEGREE SIGN -->
<!ENTITY ordm   "&#x00BA;"> <!-- MASCULINE ORDINAL INDICATOR -->
<!ENTITY ordf   "&#x00AA;"> <!-- FEMININE ORDINAL INDICATOR -->
<!ENTITY sect   "&#x00A7;"> <!-- SECTION SIGN -->
<!ENTITY para   "&#x00B6;"> <!-- PILCROW SIGN -->
<!ENTITY middot "&#x00B7;"> <!-- MIDDLE DOT -->
<!ENTITY larr   "&#x2190;"> <!-- LEFTWARDS DOUBLE ARROW -->
<!ENTITY rarr   "&#x2192;"> <!-- RIGHTWARDS DOUBLE ARROW -->
<!ENTITY uarr   "&#x2191;"> <!-- UPWARDS ARROW -->
<!ENTITY darr   "&#x2193;"> <!-- DOWNWARDS ARROW -->
<!ENTITY copy   "&#x00A9;"> <!-- COPYRIGHT SIGN -->
<!ENTITY reg    "&#x00AE;"> <!-- REG TRADE MARK SIGN -->
<!ENTITY trade  "&#x2122;"> <!-- TRADE MARK SIGN -->
<!ENTITY brvbar "&#x00A6;"> <!-- BROKEN BAR -->
<!ENTITY not    "&#x00AC;"> <!-- NOT SIGN -->
<!ENTITY sung   "&#x2669;"> <!--  -->
<!ENTITY excl   "&#x0021;"> <!-- EXCLAMATION MARK -->
<!ENTITY iexcl  "&#x00A1;"> <!-- INVERTED EXCLAMATION MARK -->
<!ENTITY quot   "&#x0022;"> <!-- QUOTATION MARK -->
<!ENTITY apos   "&#x0027;"> <!-- APOSTROPHE -->
<!ENTITY lpar   "&#x0028;"> <!-- LEFT PARENTHESIS -->
<!ENTITY rpar   "&#x0029;"> <!-- RIGHT PARENTHESIS -->
<!ENTITY comma  "&#x002C;"> <!-- COMMA -->
<!ENTITY lowbar "&#x005F;"> <!-- LOW LINE -->
<!ENTITY hyphen "&#xE4F8;"> <!--  -->
<!ENTITY period "&#x002E;"> <!-- FULL STOP -->
<!ENTITY sol    "&#x002F;"> <!-- SOLIDUS -->
<!ENTITY colon  "&#x003A;"> <!-- COLON -->
<!ENTITY semi   "&#x003B;"> <!-- SEMICOLON -->
<!ENTITY quest  "&#x003F;"> <!-- QUESTION MARK -->
<!ENTITY iquest "&#x00BF;"> <!-- INVERTED QUESTION MARK -->
<!ENTITY laquo  "&#x00AB;"> <!-- LEFT-POINTING DOUBLE ANGLE QUOTATION MARK -->
<!ENTITY raquo  "&#x00BB;"> <!-- RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK -->
<!ENTITY lsquo  "&#x2018;"> <!--  -->
<!ENTITY rsquo  "&#x2019;"> <!-- RIGHT SINGLE QUOTATION MARK -->
<!ENTITY ldquo  "&#x201C;"> <!--  -->
<!ENTITY rdquo  "&#x201D;"> <!-- RIGHT DOUBLE QUOTATION MARK -->
<!ENTITY nbsp   "&#x00A0;"> <!-- NO-BREAK SPACE -->
<!ENTITY shy    "&#x00AD;"> <!-- SOFT HYPHEN -->
<!ENTITY ndash  "&#x2013;">
<!ENTITY mdash  "&#x2014;">

<!ELEMENT book     (title, values?, author+, abstract, license?, version, date, part+)>
<!ATTLIST book     link CDATA #REQUIRED
                   disclaimer (articles|oldbook|draft|obsolete) #IMPLIED
                   lang CDATA #IMPLIED>
<!ELEMENT title    (#PCDATA)>
<!ELEMENT values   (key+)>
<!ELEMENT key      (#PCDATA)>
<!ATTLIST key      id CDATA #IMPLIED>
<!ELEMENT author   (#PCDATA|mail)*>
<!ATTLIST author   title CDATA #IMPLIED>
<!ELEMENT abstract (#PCDATA)>
<!ELEMENT license  EMPTY>
<!ELEMENT version  (#PCDATA)>
<!ELEMENT date     (#PCDATA)>
<!ELEMENT part     (title, abstract, chapter+)>
<!ATTLIST part     id CDATA #IMPLIED>
<!ELEMENT chapter  (title, abstract, include)>
<!ATTLIST chapter  id CDATA #IMPLIED>
<!ELEMENT section  (title, body*, subsection*)>
<!ATTLIST section  id   CDATA #IMPLIED
                   test CDATA #IMPLIED>
<!ELEMENT sections   (version, date, section+)>
<!ELEMENT subsection (title?, body+)>
<!ATTLIST subsection id   CDATA #IMPLIED
                     test CDATA #IMPLIED>
<!ELEMENT body    (%block.class;)*>
<!ATTLIST body    test CDATA #IMPLIED>
<!ELEMENT figure  EMPTY>
<!ATTLIST figure  caption CDATA #IMPLIED
          short   CDATA #IMPLIED
          link    CDATA #REQUIRED>
<!ELEMENT fig     EMPTY>
<!ATTLIST fig     short CDATA #IMPLIED
          linkto  CDATA #IMPLIED
          link    CDATA #REQUIRED>
<!ELEMENT img     EMPTY>
<!ATTLIST img     src CDATA #REQUIRED>
<!ELEMENT br      (#PCDATA)>
<!ELEMENT note    (#PCDATA|%inline.class;)*>
<!ATTLIST note    test CDATA #IMPLIED>
<!ELEMENT impo    (#PCDATA|%inline.class;)*>
<!ATTLIST impo    test CDATA #IMPLIED>
<!ELEMENT warn    (#PCDATA|%inline.class;)*>
<!ATTLIST warn    test CDATA #IMPLIED>
<!ELEMENT pre     (#PCDATA|%pre.class;)*>
<!ATTLIST pre     caption CDATA #REQUIRED
                  test CDATA #IMPLIED>
<!ELEMENT p       (#PCDATA|%inline.class;)*>
<!ATTLIST p       by   CDATA #IMPLIED
                  test CDATA #IMPLIED>
<!ELEMENT table   (tcolumn*, tr+)>
<!ATTLIST table   test CDATA #IMPLIED>
<!ELEMENT tcolumn EMPTY>
<!ATTLIST tcolumn width CDATA #REQUIRED>
<!ELEMENT tr      (th|ti)+>
<!ATTLIST tr      id   CDATA #IMPLIED
                  test CDATA #IMPLIED>
<!ELEMENT th      (#PCDATA|%inline.class;)*>
<!ATTLIST th      colspan CDATA #IMPLIED
                  rowspan CDATA #IMPLIED>
<!ELEMENT ti      (#PCDATA|%inline.class;)*>
<!ATTLIST ti      colspan CDATA #IMPLIED
                  rowspan CDATA #IMPLIED
                  align (left|center|right) "left">
<!ELEMENT dl      (dt|dd)+>
<!ELEMENT dt      (#PCDATA|%inline.class;)*>
<!ELEMENT dd      (#PCDATA|%inline.class;|ul|ol)*>
<!ELEMENT ul      (li+)>
<!ATTLIST ul      test CDATA #IMPLIED>
<!ELEMENT ol      (li+)>
<!ATTLIST ol      test CDATA #IMPLIED>
<!ELEMENT li      (#PCDATA|%inline.class;|ul|ol)*>
<!ATTLIST li      test CDATA #IMPLIED>

<!--STYLE TAGS-->
<!ELEMENT sup     (#PCDATA|%inline.class;)*>
<!ELEMENT sub     (#PCDATA|%inline.class;)*>
<!ELEMENT b       (#PCDATA|%inline.class;)*>
<!ELEMENT brite   (#PCDATA|%inline.class;)*>
<!ELEMENT c       (#PCDATA|%inline.class;)*>
<!ELEMENT e       (#PCDATA|%inline.class;)*>
<!ELEMENT path    (#PCDATA|%inline.class;)*>
<!ELEMENT comment (#PCDATA|%pre.class;|b)*>
<!ELEMENT i       (#PCDATA|%pre.class;)*>
<!ELEMENT keyword (#PCDATA|%pre.class;)*>
<!ELEMENT ident   (#PCDATA|%pre.class;)*>
<!ELEMENT const   (#PCDATA|%pre.class;)*>
<!ELEMENT stmt    (#PCDATA|%pre.class;)*>
<!ELEMENT var     (#PCDATA|%pre.class;)*>

<!ELEMENT keyval  EMPTY>
<!ATTLIST keyval  id CDATA #REQUIRED>

<!--LINK TAGS-->
<!ELEMENT mail      (#PCDATA)*>
<!ATTLIST mail      link CDATA #REQUIRED>
<!ELEMENT uri     (#PCDATA|img)*>
<!ATTLIST uri     link CDATA #IMPLIED>
<!ELEMENT include (#PCDATA)>
<!ATTLIST include href CDATA #REQUIRED>

=== r0bertz/gentoo-cn/doc/zh_cn/handbook/2007.0/handbook-x86.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE book SYSTEM "/dtd/book.dtd">

<!-- $Header: /var/cvsroot/gentoo/xml/htdocs/doc/zh_cn/handbook/2007.0/handbook-x86.xml,v 1.2 2007/09/14 17:37:36 r0bertz Exp $ -->
<!-- English CVS version: 1.9 -->

<book link="/doc/zh_cn/handbook/2007.0/handbook-x86.xml" lang="zh_cn" disclaimer="oldbook">
<title>Gentoo Linux 2007.0 x86无网络手册</title>

<values>
 <key id="arch">x86</key>
 <key id="release-dir">releases/x86/2007.0/</key>
 <key id="online-book">2007.0/handbook-x86.xml</key>
</values>

<author title="作者">
  <mail link="swift@gentoo.org">Sven Vermeulen</mail>
</author>
<author title="作者">
  <mail link="g2boojum@gentoo.org">Grant Goodyear</mail>
</author>
<author title="作者">
  <mail link="uberlord@gentoo.org">Roy Marples</mail>
</author>
<author title="作者">
    <mail link="drobbins@gentoo.org">Daniel Robbins</mail>
</author>
<author title="作者">
  <mail link="chouser@gentoo.org">Chris Houser</mail>
</author>
<author title="作者">
  <mail link="jerry@gentoo.org">Jerry Alexandratos</mail>
</author>
<author title="作者">
  <mail link="nightmorph@gentoo.org">Joshua Saddler</mail>
</author>
<author title="Gentoo x86开发人员">
  <mail link="seemant@gentoo.org">Seemant Kulleen</mail>
</author>
<author title="Gentoo Alpha开发人员">
  <mail link="taviso@gentoo.org">Tavis Ormandy</mail>
</author>
<author title="Gentoo AMD64开发人员">
  <mail link="jhuebel@gentoo.org">Jason Huebel</mail>
</author>
<author title="Gentoo HPPA开发人员">
  <mail link="gmsoft@gentoo.org">Guy Martin</mail>
</author>
<author title="Gentoo PPC开发人员">
   <mail link="pvdabeel@gentoo.org">Pieter Van den Abeele</mail>
</author>
<author title="Gentoo SPARC开发人员">
  <mail link="blademan@gentoo.org">Joe Kallar</mail>
</author>
<author title="编辑">
    <mail link="zhen@gentoo.org">John P. Davis</mail>
</author>
<author title="编辑">Pierre-Henri Jondot</author>
<author title="编辑">
    <mail link="stocke2@gentoo.org">Eric Stockbridge</mail>
</author>
<author title="编辑">
    <mail link="rajiv@gentoo.org">Rajiv Manglani</mail>
</author>
<author title="编辑">
    <mail link="seo@gentoo.org">Jungmin Seo</mail>
</author>
<author title="编辑">
    <mail link="zhware@gentoo.org">Stoyan Zhekov</mail>
</author>
<author title="编辑">
    <mail link="jhhudso@gentoo.org">Jared Hudson</mail>
</author>
<author title="编辑">
    <mail link="peitolm@gentoo.org">Colin Morey</mail>
</author>
<author title="编辑">
    <mail link="peesh@gentoo.org">Jorge Paulo</mail>
</author>
<author title="编辑">
    <mail link="carl@gentoo.org">Carl Anderson</mail>
</author>
<author title="编辑">
    <mail link="avenj@gentoo.org">Jon Portnoy</mail>
</author>
<author title="编辑">
     <mail link="klasikahl@gentoo.org">Zack Gilburd</mail>
</author>
<author title="编辑">
  <mail link="jmorgan@gentoo.org">Jack Morgan</mail>
</author>
<author title="编辑">
  <mail link="bennyc@gentoo.org">Benny Chuang</mail>
</author>
<author title="编辑">
  <mail link="erwin@gentoo.org">Erwin</mail>
</author>
<author title="编辑">
  <mail link="kumba@gentoo.org">Joshua Kinard</mail>
</author>
<author title="编辑">
  <mail link="dertobi123@gentoo.org">Tobias Scherbaum</mail>
</author>
<author title="编辑">
  <mail link="neysx@gentoo.org">Xavier Neys</mail>
</author>
<author title="编辑">
  <mail link="fox2mike@gentoo.org">Shyam Mani</mail>
</author>
<author title="审校">
    <mail link="gerrynjr@gentoo.org">Gerald J. Normandin Jr.</mail>
</author>
<author title="审校">
    <mail link="dberkholz@gentoo.org">Donnie Berkholz</mail>
</author>
<author title="审校">
    <mail link="antifa@gentoo.org">Ken Nowack</mail>
</author>
<author title="投稿">
   <mail link="pylon@gentoo.org">Lars Weiler</mail>
</author>
<author title="译者">
  <mail link="gnuguys@gmail.com">杨珂</mail>
</author>
<author title="译者">
  <mail link="tysnoo@gmail.com">叶宝泰</mail>
</author>
<author title="译者">
  <mail link="r0bertz@gentoo.org">张乐</mail>
</author>
<author title="译者">
  <mail link="daqiehexigua@gmail.com">余雷</mail>
</author>
<author title="译者">
  <mail link="zhudingshibai@gmail.com">王国辉</mail>
</author>
<author title="译者">
  <mail link="dongbin.lou@gmail.com">娄东斌</mail>
</author>
<author title="译者">
  <mail link="linuxjia@gmail.com">贾震</mail>
</author>
<author title="译者">
  <mail link="druggo@gmail.com">杨小广</mail>
</author>
<author title="译者">
  <mail link="acevery@gmail.com">余鈺炜</mail>
</author>
<author title="译者">
  <mail link="coolshoulder@gmail.com">陈代焱</mail>
</author>
<author title="译者">
  <mail link="linuxfans.linky@gmail.com">范华</mail>
</author>
<author title="译者">
  <mail link="greyeye.cn@gmail.com">陈永骥</mail>
</author>
<author title="译者">
  <mail link="chenjun.shen@gmail.com">沈辰俊</mail>
</author>

<abstract>
Gentoo无网络手册目的是要将Gentoo/Linux的相关资料都集中收编在一起。本手册包含在x86平台无网络条件下安装操作指南以及讲述如何使用Gentoo和Portage的章节。
</abstract>


<!-- The content of this document is licensed under the CC-BY-SA license -->
<!-- See http://creativecommons.org/licenses/by-sa/2.5 -->
<license/>

<version>8.1</version>
<date>2007-06-06</date>

<part>
<title>安装Gentoo</title>
<abstract>
在这部分中，你将学习如何在你的系统中安装Gentoo。
</abstract>

<chapter>
<title>关于如何安装Gentoo Linux</title>
<abstract>
不熟悉Gentoo的用户并不总是了解Gentoo就意味着选择。
</abstract>
  <include href="hb-install-about.xml"/>
</chapter>

<chapter>
<title>启动安装程序LiveCD</title>
<abstract>
使用我们的安装程序LiveCD你可以使你的系统启动到一个可运行的环境中以便安装Gentoo。
</abstract>
  <include href="hb-install-gli-medium.xml"/>
</chapter>

<chapter>
<title>使用基于GTK+的Gentoo Linux安装程序</title>
<abstract>
你现在可以选择使用我们的图形化安装程序安装Gentoo。使用一个易用的GUI界面来配置你所需要的选项，然后就可以开始安装进程。
</abstract>
  <include href="hb-install-gtkfe.xml" />
</chapter>

<chapter>
<title>使用基于Dialog的Gentoo Linux安装程序</title>
<abstract>
你可以选择使用我们文本模式的安装程序安装Gentoo。使用一组易用的菜单来配置你所需的选项，然后就可以开始安装进程。
</abstract>
  <include href="hb-install-gli-dialog.xml" />
</chapter>

<chapter>
<title>下一步该做什么？</title>
<abstract>
现在你已经拥有了你自己的Gentoo操作系统了，但是下一步该做什么呢？
</abstract>
  <include href="hb-install-next.xml"/>
</chapter>
</part>

<part>
<title>使用Gentoo</title>
<abstract>
学习如何使用Gentoo：安装软件，更改变量，改变Portage行为方式等。
</abstract>

<chapter>
<title>Portage入门</title>
<abstract>
这一章节讲解了用户最起码要了解的如何在他的系统上维护软件的“简单”步骤。
</abstract>
  <include href="../hb-working-portage.xml"/>
</chapter>

<chapter>
<title>USE标记</title>
<abstract>
USE标记是Gentoo非常重要的一部分。在本章里，你将学习设定USE标记以及了解USE标记如何影响你的系统构建。
</abstract>
  <include href="../hb-working-use.xml"/>
</chapter>

<chapter>
<title>Portage特性</title>
<abstract>
揭示Portage拥有的一些特性，比如支持分布式编译，ccache等等。
</abstract>
  <include href="../hb-working-features.xml"/>
</chapter>

<chapter>
<title>初始化脚本</title>
<abstract>
Gentoo使用一种特殊的初始化脚本格式，在其众多的特色之中包括了允许依赖关系驱动的决定和虚拟的初始化脚本。本章会解释所有这些特色以及如何与这些脚本打交道。
</abstract>
  <include href="../hb-working-rcscripts.xml"/>
</chapter>

<chapter>
<title>环境变量</title>
<abstract>
使用Gentoo你可以容易地管理你系统中的环境变量。本章会解释管理方式以及描述一些经常会使用到的变量。
</abstract>
  <include href="../hb-working-variables.xml"/>
</chapter>
</part>

<part>
<title>使用Portage</title>
<abstract>
“使用Portage”深入全面介绍了Gentoo的软件管理工具Portage的功能。
</abstract>

<chapter>
<title>文件和目录</title>
<abstract>
当你想要深入了解Portage的时候，你需要知道它将文件和数据放在了什么地方。
</abstract>
  <include href="../hb-portage-files.xml"/>
</chapter>

<chapter>
<title>通过变量来配置</title>
<abstract>
你可以通过在配置文件里或者环境变量里设定的各种变量来全面的配置Portage。
</abstract>
  <include href="../hb-portage-configuration.xml"/>
</chapter>

<chapter>
<title>使用多个软件分支</title>
<abstract>
Gentoo根据软件的稳定性和架构支持将它们划分在不同的分支中。“使用多个软件分支”告诉你这些分支是如何配置的以及如何在个别情况下使用其他分支的软件。
</abstract>
  <include href="../hb-portage-branches.xml"/>
</chapter>

<chapter>
<title>Portage附加工具</title>
<abstract>
您可以通过Portage提供的一些附加工具为您的Gentoo旅程带来更多的快乐。通过下文的阅读你会学会如何使用dispatch-conf和其他的一些工具。
</abstract>
  <include href="../hb-portage-tools.xml"/>
</chapter>

<chapter>
<title>改造Portage树</title>
<abstract>
“改造Portage树”提供给你一些关于如何使用你自己的Portage树，如何只同步你想要的分类，加入自己的软件包等等的心得技巧。
</abstract>
  <include href="../hb-portage-diverttree.xml"/>
</chapter>
</part>

<part>
<title>Gentoo网络配置</title>
<abstract>一份全面的Gentoo网络指南。</abstract>

<chapter>
<title>新手上路</title>
<abstract>
一份能快速启动你的网络设备，并使之在大多数情况下能运转正常的指南。
</abstract>
<include href="../hb-net-start.xml"/>
</chapter>

<chapter>
<title>高级配置</title>
<abstract>
这儿我们将学习到这些配置是如何工作的——在我们开始学习模块化网络前你必须先弄懂这个。
</abstract>
<include href="../hb-net-advanced.xml"/>
</chapter>

<chapter>
<title>模块化网络</title>
<abstract>
Gentoo提供了灵活多变的组网方式——在这里你将会了解到选择不同的DHCP客户端，设置Bonding，桥接，VLAN等等。
</abstract>
<include href="../hb-net-modules.xml"/>
</chapter>

<chapter>
<title>无线网络</title>
<abstract>
无线网络的设定不是很容易。希望我们的介绍可以让你的网络工作起来！
</abstract>
<include href="../hb-net-wireless.xml"/>
</chapter>

<chapter>
<title>附加功能</title>
<abstract>
如果你敢于冒险，你可以为你的网络添加个性化的功能。
</abstract>
<include href="../hb-net-functions.xml"/>
</chapter>

<chapter>
<title>网络管理</title>
<abstract>
这部分是为那些使用笔记本的用户和经常在不同的网络中移动他们的电脑的人准备的。
</abstract>
<include href="../hb-net-management.xml"/>
</chapter>
</part>

</book>

=== r0bertz/gentoo-cn/handbook/2007.0/hb-install-next.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet type="text/xsl" href="/xsl/guide.xsl" ?>
<!DOCTYPE sections SYSTEM "/dtd/book.dtd">

<!-- The content of this document is licensed under the CC-BY-SA license -->
<!-- See http://creativecommons.org/licenses/by-sa/2.5 -->

<!-- $Header: /var/cvsroot/gentoo/xml/htdocs/doc/en/handbook/2007.0/hb-install-next.xml,v 1.4 2007/05/07 18:11:42 nightmorph Exp $ -->

<sections>

<version>8.0</version>
<date>2007-05-07</date>

<section>
<title>文档</title>
<subsection>
<body>

<p>
恭喜！您现在拥有了一个可以运转的Gentoo系统。但接下来往何处去？现在您拥有什么样的选择？先探索些什么？Gentoo为它的用户提供了大量的可能性，因此也有大量已经提供文档（少量没有）的特性。
</p>

<p>
您无疑应该先看一下Gentoo手册里标题为<uri link="?part=2">在Gentoo中工作</uri>的那一章节，那里解释了如何保证您随时用上最新的软件，如何安装更多的软件，什么是USE标记，以及Gentoo Init系统是如何工作的等等。
</p>

<p>
如果您有兴趣对系统进行优化以使其适合桌面应用，或者您想了解如何将您的系统配置成一个完整可用的桌面系统，请参阅我们所提供的全面的<uri link="/doc/zh_cn/index.xml?catid=desktop">Gentoo桌面文档资源</uri>。另外，我们也提供<uri link="/doc/zh_cn/guide-localization.xml">本地化指南</uri>供您参考，利用它您可以使您的系统看起来更加本地化。
</p>

<p>
我们还提供了一份值得您阅读的<uri link="/doc/zh_cn/security/">Gentoo安全手册</uri>
</p>

<p>
您如果想得到一份我们已有的可用文档的列表，请查看我们提供的<uri link="/doc/zh_cn/index.xml">文档资源</uri>页面。
</p>

</body>
</subsection>
</section>
<section>
<title>线上Gentoo</title>
<body>

<p>
当然也非常欢迎您加入我们的<uri link="http://forums.gentoo.org">Gentoo论坛</uri>或者我们建立的<uri link="/main/en/irc.xml">Gentoo IRC 频道</uri>中的任意一个。
</p>

<p>
我们也有一些<uri link="/main/en/lists.xml">邮件列表</uri>是面对所有用户开放的。加入列表的方法已包含在前述页面中。
</p>

<p>
现在，我们将保持安静，以便让您享受您的安装过程。
</p>

</body>
</section>
<section>
<title>由2007.0版以来Gentoo的变更</title>
<subsection>
<title>变更？</title>
<body>

<p>
Gentoo是一个更新快速的发行版。接下来的章节将为您描述一些会影响Gentoo安装的重要的变更。我们只列出那些在安装中通常会遇到的，那些在安装中不会发生变化的包将不会给出。
</p>

<p>
到目前为止还没有重要的变更。
</p>

</body>
</subsection>
</section>
</sections>

=== r0bertz/gentoo-cn/doc/cn/devhb/handbook.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet type="text/xsl" href="/xsl/guide.xsl" ?>
<!DOCTYPE book SYSTEM "/dtd/book.dtd">

<!-- $Header: /var/www/www.gentoo.org/raw_cvs/gentoo/xml/htdocs/proj/en/devrel/handbook/handbook.xml,v 1.3 2004/08/24 21:07:26 plasmaroo Exp $ -->

<book link="handbook.xml">
  <title>Gentoo开发手册</title>

  <!-- Ebuild HOWTO -->
  <author title="Ebuild HOWTO - Author">
    Donny Davies<!-- No longer a developer; unknown@... -->
  </author>
  <author title="Author">
    <mail link="pete@gentoo.org">Peter Gavin</mail>
  </author>
  <author title="Author">
    <mail link="karltk@gentoo.org">Karl Trygve Kalleberg</mail>
  </author>
  <author title="Author">
    <mail link="vapier@gentoo.org">Mike Frysinger</mail>
  </author>
  <author title="Author/Editor">
    <mail link="drobbins@gentoo.org">Daniel Robbins</mail>
  </author>
  <author title="Author/Editor"><!-- zhen@gentoo.org -->
    John P. Davis
  </author>
  <author title="Editor">
    <mail link="peesh@gentoo.org">Jorge Paulo</mail>
  </author>
  <author title="Editor">
    <mail link="swift@gentoo.org">Sven Vermeulen</mail>
  </author>
  <author title="Editor">
    <mail link="klasikahl@gentoo.org">Zack Gilburd</mail>
  </author>
  <author title="Editor">
    <mail link="bennyc@gentoo.org">Benny Chuang</mail>
  </author>
  <author title="Editor">
    <mail link="erwin@gentoo.org">Erwin</mail>
  </author>

  <!-- :: EClass HOWTO -->

  <!-- Zhen; mentioned above... -->
  <author title = "Eclass HOWTO - Author">
    <mail link="danarmak@gentoo.org">Dan Armak</mail>
  </author>

  <!-- :: Common mistakes -->
  
  <author title="Common Ebuild Mistakes - Author">
    <mail link="liquidx@gentoo.org">Alastair Tse</mail>
  </author>
  
  <!-- :: Metadata -->

  <!-- SwifT; mentioned above... -->
  <author title="Metadata Document - Author">
    <mail link="pauldv@gentoo.org">Paul De Vrieze</mail>
  </author>

  <!-- Ebuild policy -->

  <!-- drobbins, karltk, liquidx, vapier, SwifT mentioned above... -->
  <author title="Ebuild Policy - Original Author">Owen Stampflee</author> 
  <author title="Editor">
    <mail link="seemant@gentoo.org">Seemant Kulleen</mail>
  </author> 
  <author title="Editor">
    <mail link="avenj@gentoo.org">Jon Portnoy</mail>
  </author>
  <author title="Editor">
    <mail link="carl@gentoo.org">Carl Anderson</mail>
  </author>

  <author title="Contributor">
    <mail link="ciaranm@gentoo.org">Ciaran McCreesh</mail>
  </author>

  <author title="Author/Editor">
    <mail link="plasmaroo@gentoo.org">Tim Yamin</mail>
  </author>

  <author title="Editors">
    Gentoo Developer Relations Team
  </author>

  <author title="Translator">
    <mail link="joanphan@gmail.com">Hans Joanphan</mail>
  </author>

  <abstract>
    This is the Gentoo Developer Handbook, a continuing effort to
    centralize development policies across Gentoo and to also outline
    Gentoo's development systems and procedures.
  </abstract>

  <!-- The content of this document is licensed under the CC-BY-SA license -->
  <!-- See http://creativecommons.org/licenses/by-sa/1.0 -->
  <license/>

  <version>1.0</version>
  <date>August 08, 2004</date>

  <part>
    <title>介绍</title>
    <abstract>
      这个部分覆盖了Gentoo的开发绝大部分的领域。这部分只是对于一个Gentoo开发者才有关系，否则你可以跳过这一部分。
    </abstract>

    <chapter>
      <title>介绍</title>
      <abstract>
	这一节概括了Gentoo开发手册的目的。
      </abstract>
      <include href="hb-introduction.xml"/>
    </chapter>

    <chapter>
      <title>成为一个开发者</title>
      <abstract>
	这一节主要要解释怎样成为一个Gentoo开发者
      </abstract>
      <include href="hb-introduction-becoming-a-dev.xml"/>
    </chapter>

    <chapter>
      <title>你将获得什么</title>
      <abstract>
	这一节概述了对于Gentoo开发者提供的服务。
      </abstract>
      <include href="hb-introduction-whatyouget.xml"/>
    </chapter>

    <chapter>
      <title>帮助新开发人员</title>
      <abstract>
	这部分给新的开发人员提供了帮助和指南。
      </abstract>
      <include href="hb-introduction-new-devs.xml"/>
    </chapter>

    <chapter>
      <title>开发者的等级</title>
      <abstract>
	这一节概述了Gentoo开发者和开发的等级。
      </abstract>
      <include href="hb-introduction-hierachy.xml"/>
    </chapter>
  </part>

  <part>
    <title>手册</title>
    <abstract>
      这一节概述和解释了不同的开发过程，并给Gentoo开发人员提供标准。
    </abstract>

    <chapter>
      <title>Ebuild手册</title>
      <abstract>
	这一节描述了Gentoo Linux的Portage系统，怎样为Gentoo创建新的软件包，在某一程度上也是Gentoo开发人员的标准。这是进程中的一个状态，还会不断的更新和改变，永远都不会结束。你应该联合这篇文档和Portage提供的man页面（特别是ebuild(5)）以及Gentoo Linux开发策略来使用。
      </abstract>
      <include href="hb-guide-ebuild.xml"/>
    </chapter>

    <chapter>
      <title>Eclass手册</title>
      <abstract>
	这一节用于提高给开发者一个eclass怎样工作和怎样应用到ebuild的详细指南。
      </abstract>
      <include href="hb-guide-eclass.xml"/>
    </chapter>

    <chapter>
      <title>常见的ebuild错误</title>
      <abstract>
	这一节解释了贡献者和开发者在书写和提交ebuild时常常出现的错误。
      </abstract>
      <include href="hb-guide-common-mistakes.xml"/>
    </chapter>

    <chapter>
      <title>Gentoo Metadata</title>
      <abstract>
	这一节解释了用于Portage树里的必要性和使用方法。
      </abstract>
      <include href="hb-guide-metadata.xml"/>
    </chapter>

    <chapter>
      <title>Ebuild维护手册</title>
      <abstract>
	这一节描述了在维护Portage树里的Ebuild时开发者执行日常工作的过程。
      </abstract>
      <include href="hb-guide-ebuild-maintaining.xml"/>
    </chapter>
  </part>

  <part>
    <title>策略</title>
    <abstract>
      这部分覆盖了开发者提交项目到CVS时需遵守的策略和方针。
    </abstract>

    <chapter>
      <title>Ebuild的策略</title>
      <abstract>
	这一节概述了Portage里每个ebuild必须遵守的策略。
      </abstract>
      <include href="hb-policy-ebuild.xml"/>
    </chapter>

    <chapter>
      <title>Etiquette的策略</title>
      <abstract>
	这一节概述了Gentoo开发者的礼仪策略。
      </abstract>
      <include href="hb-policy-etiquette.xml"/>
    </chapter>
  </part>

<!--
  <part>
    <title>Appendix 1: Management</title>
    <abstract>
      This part covers managerial policies.
    </abstract>
  </part>
-->

</book>

=== r0bertz/gentoo-cn/doc/zh_cn/security/shb-mounting.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- $Header$ -->
<!-- English CVS version: 1.4 -->
<!DOCTYPE sections SYSTEM "/dtd/book.dtd">
<!-- The content of this document is licensed under the CC-BY-SA license 
 See http://creativecommons.org/licenses/by-sa/1.0 -->
<sections>

<version>1.0</version>
<date>2005-05-31</date>

<section>
<title>挂载分区</title>
<body>

<p>
在挂载一个<c>ext2</c>，<c>ext3</c>或者<c>reiserfs</c>格式的分区的时候，你有几个能够加入到<path>/etc/fstab</path>里面的选项。这些选项是：
</p>

<ul>
<li>
  <c>nosuid</c> － 忽略SUID bit，并且使它像一个正常文件一样
</li>
<li>
  <c>noexec</c> - 阻止来自这个分区的文件的执行
</li>
<li>
  <c>nodev</c> - 忽略设备
</li>
</ul>

<p>
很不幸的是，这些选项可以很容易地通过一个间接的途径而被绕过。然而，把<path>/tmp</path>设置成noexec模式能阻止大多数需要直接从/tmp里执行的漏洞攻击程序的攻击。
</p>

<pre caption="/etc/fstab">
/dev/sda1 /boot ext2 noauto,noatime 1 1
/dev/sda2 none swap sw 0 0
/dev/sda3 / reiserfs notail,noatime 0 0
/dev/sda4 /tmp reiserfs notail,noatime,nodev,nosuid,noexec 0 0
/dev/sda5 /var reiserfs notail,noatime,nodev 0 0
/dev/sda6 /home reiserfs notail,noatime,nodev,nosuid 0 0
/dev/sda7 /usr reiserfs notail,noatime,nodev,ro 0 0
/dev/cdroms/cdrom0 /mnt/cdrom iso9660 noauto,ro 0 0
proc /proc proc defaults 0 0
</pre>

<warn>
把<path>/tmp</path>设置成<c>noexec</c>模式可以阻止某些脚本的正确运行。
</warn>

<note>
更多有关磁盘限额的信息请查看<uri 
link="?part=1&amp;chap=5#quotas">磁盘限额</uri>。
</note>

<note>
即使来自<path>/var</path>的文件通常是永远不会被执行,我也没有给它加上<c>noexec</c>或者<c>nosuid</c>选项，这是因为我安装了netqmail，它被安装在<path>/var/qmail</path>，并且它必须被允许执行和处理一个SUID文件。
除非我要升级Gentoo，否则我把<path>/usr</path>设置成只读模式，这是因为我除了升级以外从来不写任何东西到那里面去。在我要升级Gentoo的时候，我会重新用读写模式挂载文件系统，接着升级，最后再次使用只读模式挂载它。
</note>

<note>
即使你不用netqmail，Gentoo仍然需要你给<path>/var/tmp</path>设置可运行选项，因为ebuild是在这里生成的。但是如果你坚持把<path>/var</path>挂载成<c>noexec</c>模式，还有一个可替代的路径设置。</note>

</body>
</section>
</sections>
