=== r0bertz/gentoo-cn/dtd/book.dtd
<!ENTITY  % inline.class "sup|sub|b|brite|c|e|path|img|br|mail|uri|keyval">
<!ENTITY  % pre.class    "comment|i|keyword|ident|const|stmt|var|keyval">
<!ENTITY  % block.class  "figure|fig|note|impo|warn|pre|p|table|ul|ol|dl">

<!ENTITY half   "&#x00BD;"> <!-- VULGAR FRACTION ONE HALF -->
<!ENTITY frac12 "&#x00BD;"> <!-- VULGAR FRACTION ONE HALF -->
<!ENTITY frac14 "&#x00BC;"> <!-- VULGAR FRACTION ONE QUARTER -->
<!ENTITY frac34 "&#x00BE;"> <!-- VULGAR FRACTION THREE QUARTERS -->
<!ENTITY frac18 "&#x215B;"> <!--  -->
<!ENTITY frac38 "&#x215C;"> <!--  -->
<!ENTITY frac58 "&#x215D;"> <!--  -->
<!ENTITY frac78 "&#x215E;"> <!--  -->
<!ENTITY sup1   "&#x00B9;"> <!-- SUPERSCRIPT ONE -->
<!ENTITY sup2   "&#x00B2;"> <!-- SUPERSCRIPT TWO -->
<!ENTITY sup3   "&#x00B3;"> <!-- SUPERSCRIPT THREE -->
<!ENTITY plus   "&#x002B;"> <!-- PLUS SIGN -->
<!ENTITY plusmn "&#x00B1;"> <!-- PLUS-MINUS SIGN -->
<!ENTITY lt     "&#38;#60;"> <!-- LESS-THAN SIGN -->
<!ENTITY equals "&#x003D;"> <!-- EQUALS SIGN -->
<!ENTITY gt     "&#x003E;"> <!-- GREATER-THAN SIGN -->
<!ENTITY divide "&#x00F7;"> <!-- DIVISION SIGN -->
<!ENTITY times  "&#x00D7;"> <!-- MULTIPLICATION SIGN -->
<!ENTITY curren "&#x00A4;"> <!-- CURRENCY SIGN -->
<!ENTITY pound  "&#x00A3;"> <!-- POUND SIGN -->
<!ENTITY dollar "&#x0024;"> <!-- DOLLAR SIGN -->
<!ENTITY cent   "&#x00A2;"> <!-- CENT SIGN -->
<!ENTITY yen    "&#x00A5;"> <!-- YEN SIGN -->
<!ENTITY num    "&#x0023;"> <!-- NUMBER SIGN -->
<!ENTITY percnt "&#x0025;"> <!-- PERCENT SIGN -->
<!ENTITY amp    "&#38;#38;"> <!-- AMPERSAND -->
<!ENTITY ast    "&#x2217;"> <!-- ASTERISK OPERATOR -->
<!ENTITY commat "&#x0040;"> <!-- COMMERCIAL AT -->
<!ENTITY lsqb   "&#x005B;"> <!-- LEFT SQUARE BRACKET -->
<!ENTITY bsol   "&#x005C;"> <!-- REVERSE SOLIDUS -->
<!ENTITY rsqb   "&#x005D;"> <!-- RIGHT SQUARE BRACKET -->
<!ENTITY lcub   "&#x007B;"> <!-- LEFT CURLY BRACKET -->
<!ENTITY horbar "&#x2015;"> <!-- HORIZONTAL BAR -->
<!ENTITY verbar "&#x007C;"> <!-- VERTICAL LINE -->
<!ENTITY rcub   "&#x007D;"> <!-- RIGHT CURLY BRACKET -->
<!ENTITY micro  "&#x00B5;"> <!-- MICRO SIGN -->
<!ENTITY ohm    "&#x2126;"> <!-- OHM SIGN -->
<!ENTITY deg    "&#x00B0;"> <!-- DEGREE SIGN -->
<!ENTITY ordm   "&#x00BA;"> <!-- MASCULINE ORDINAL INDICATOR -->
<!ENTITY ordf   "&#x00AA;"> <!-- FEMININE ORDINAL INDICATOR -->
<!ENTITY sect   "&#x00A7;"> <!-- SECTION SIGN -->
<!ENTITY para   "&#x00B6;"> <!-- PILCROW SIGN -->
<!ENTITY middot "&#x00B7;"> <!-- MIDDLE DOT -->
<!ENTITY larr   "&#x2190;"> <!-- LEFTWARDS DOUBLE ARROW -->
<!ENTITY rarr   "&#x2192;"> <!-- RIGHTWARDS DOUBLE ARROW -->
<!ENTITY uarr   "&#x2191;"> <!-- UPWARDS ARROW -->
<!ENTITY darr   "&#x2193;"> <!-- DOWNWARDS ARROW -->
<!ENTITY copy   "&#x00A9;"> <!-- COPYRIGHT SIGN -->
<!ENTITY reg    "&#x00AE;"> <!-- REG TRADE MARK SIGN -->
<!ENTITY trade  "&#x2122;"> <!-- TRADE MARK SIGN -->
<!ENTITY brvbar "&#x00A6;"> <!-- BROKEN BAR -->
<!ENTITY not    "&#x00AC;"> <!-- NOT SIGN -->
<!ENTITY sung   "&#x2669;"> <!--  -->
<!ENTITY excl   "&#x0021;"> <!-- EXCLAMATION MARK -->
<!ENTITY iexcl  "&#x00A1;"> <!-- INVERTED EXCLAMATION MARK -->
<!ENTITY quot   "&#x0022;"> <!-- QUOTATION MARK -->
<!ENTITY apos   "&#x0027;"> <!-- APOSTROPHE -->
<!ENTITY lpar   "&#x0028;"> <!-- LEFT PARENTHESIS -->
<!ENTITY rpar   "&#x0029;"> <!-- RIGHT PARENTHESIS -->
<!ENTITY comma  "&#x002C;"> <!-- COMMA -->
<!ENTITY lowbar "&#x005F;"> <!-- LOW LINE -->
<!ENTITY hyphen "&#xE4F8;"> <!--  -->
<!ENTITY period "&#x002E;"> <!-- FULL STOP -->
<!ENTITY sol    "&#x002F;"> <!-- SOLIDUS -->
<!ENTITY colon  "&#x003A;"> <!-- COLON -->
<!ENTITY semi   "&#x003B;"> <!-- SEMICOLON -->
<!ENTITY quest  "&#x003F;"> <!-- QUESTION MARK -->
<!ENTITY iquest "&#x00BF;"> <!-- INVERTED QUESTION MARK -->
<!ENTITY laquo  "&#x00AB;"> <!-- LEFT-POINTING DOUBLE ANGLE QUOTATION MARK -->
<!ENTITY raquo  "&#x00BB;"> <!-- RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK -->
<!ENTITY lsquo  "&#x2018;"> <!--  -->
<!ENTITY rsquo  "&#x2019;"> <!-- RIGHT SINGLE QUOTATION MARK -->
<!ENTITY ldquo  "&#x201C;"> <!--  -->
<!ENTITY rdquo  "&#x201D;"> <!-- RIGHT DOUBLE QUOTATION MARK -->
<!ENTITY nbsp   "&#x00A0;"> <!-- NO-BREAK SPACE -->
<!ENTITY shy    "&#x00AD;"> <!-- SOFT HYPHEN -->
<!ENTITY ndash  "&#x2013;">
<!ENTITY mdash  "&#x2014;">

<!ELEMENT book     (title, values?, author+, abstract, license?, version, date, part+)>
<!ATTLIST book     link CDATA #REQUIRED
                   disclaimer (articles|oldbook|draft|obsolete) #IMPLIED
                   lang CDATA #IMPLIED>
<!ELEMENT title    (#PCDATA)>
<!ELEMENT values   (key+)>
<!ELEMENT key      (#PCDATA)>
<!ATTLIST key      id CDATA #IMPLIED>
<!ELEMENT author   (#PCDATA|mail)*>
<!ATTLIST author   title CDATA #IMPLIED>
<!ELEMENT abstract (#PCDATA)>
<!ELEMENT license  EMPTY>
<!ELEMENT version  (#PCDATA)>
<!ELEMENT date     (#PCDATA)>
<!ELEMENT part     (title, abstract, chapter+)>
<!ATTLIST part     id CDATA #IMPLIED>
<!ELEMENT chapter  (title, abstract, include)>
<!ATTLIST chapter  id CDATA #IMPLIED>
<!ELEMENT section  (title, body*, subsection*)>
<!ATTLIST section  id   CDATA #IMPLIED
                   test CDATA #IMPLIED>
<!ELEMENT sections   (version, date, section+)>
<!ELEMENT subsection (title?, body+)>
<!ATTLIST subsection id   CDATA #IMPLIED
                     test CDATA #IMPLIED>
<!ELEMENT body    (%block.class;)*>
<!ATTLIST body    test CDATA #IMPLIED>
<!ELEMENT figure  EMPTY>
<!ATTLIST figure  caption CDATA #IMPLIED
          short   CDATA #IMPLIED
          link    CDATA #REQUIRED>
<!ELEMENT fig     EMPTY>
<!ATTLIST fig     short CDATA #IMPLIED
          linkto  CDATA #IMPLIED
          link    CDATA #REQUIRED>
<!ELEMENT img     EMPTY>
<!ATTLIST img     src CDATA #REQUIRED>
<!ELEMENT br      (#PCDATA)>
<!ELEMENT note    (#PCDATA|%inline.class;)*>
<!ATTLIST note    test CDATA #IMPLIED>
<!ELEMENT impo    (#PCDATA|%inline.class;)*>
<!ATTLIST impo    test CDATA #IMPLIED>
<!ELEMENT warn    (#PCDATA|%inline.class;)*>
<!ATTLIST warn    test CDATA #IMPLIED>
<!ELEMENT pre     (#PCDATA|%pre.class;)*>
<!ATTLIST pre     caption CDATA #REQUIRED
                  test CDATA #IMPLIED>
<!ELEMENT p       (#PCDATA|%inline.class;)*>
<!ATTLIST p       by   CDATA #IMPLIED
                  test CDATA #IMPLIED>
<!ELEMENT table   (tcolumn*, tr+)>
<!ATTLIST table   test CDATA #IMPLIED>
<!ELEMENT tcolumn EMPTY>
<!ATTLIST tcolumn width CDATA #REQUIRED>
<!ELEMENT tr      (th|ti)+>
<!ATTLIST tr      id   CDATA #IMPLIED
                  test CDATA #IMPLIED>
<!ELEMENT th      (#PCDATA|%inline.class;)*>
<!ATTLIST th      colspan CDATA #IMPLIED
                  rowspan CDATA #IMPLIED>
<!ELEMENT ti      (#PCDATA|%inline.class;)*>
<!ATTLIST ti      colspan CDATA #IMPLIED
                  rowspan CDATA #IMPLIED
                  align (left|center|right) "left">
<!ELEMENT dl      (dt|dd)+>
<!ELEMENT dt      (#PCDATA|%inline.class;)*>
<!ELEMENT dd      (#PCDATA|%inline.class;|ul|ol)*>
<!ELEMENT ul      (li+)>
<!ATTLIST ul      test CDATA #IMPLIED>
<!ELEMENT ol      (li+)>
<!ATTLIST ol      test CDATA #IMPLIED>
<!ELEMENT li      (#PCDATA|%inline.class;|ul|ol)*>
<!ATTLIST li      test CDATA #IMPLIED>

<!--STYLE TAGS-->
<!ELEMENT sup     (#PCDATA|%inline.class;)*>
<!ELEMENT sub     (#PCDATA|%inline.class;)*>
<!ELEMENT b       (#PCDATA|%inline.class;)*>
<!ELEMENT brite   (#PCDATA|%inline.class;)*>
<!ELEMENT c       (#PCDATA|%inline.class;)*>
<!ELEMENT e       (#PCDATA|%inline.class;)*>
<!ELEMENT path    (#PCDATA|%inline.class;)*>
<!ELEMENT comment (#PCDATA|%pre.class;|b)*>
<!ELEMENT i       (#PCDATA|%pre.class;)*>
<!ELEMENT keyword (#PCDATA|%pre.class;)*>
<!ELEMENT ident   (#PCDATA|%pre.class;)*>
<!ELEMENT const   (#PCDATA|%pre.class;)*>
<!ELEMENT stmt    (#PCDATA|%pre.class;)*>
<!ELEMENT var     (#PCDATA|%pre.class;)*>

<!ELEMENT keyval  EMPTY>
<!ATTLIST keyval  id CDATA #REQUIRED>

<!--LINK TAGS-->
<!ELEMENT mail      (#PCDATA)*>
<!ATTLIST mail      link CDATA #REQUIRED>
<!ELEMENT uri     (#PCDATA|img)*>
<!ATTLIST uri     link CDATA #IMPLIED>
<!ELEMENT include (#PCDATA)>
<!ATTLIST include href CDATA #REQUIRED>

=== r0bertz/gentoo-cn/doc/zh_cn/handbook/draft/hb-install-alpha-kernel.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE sections SYSTEM "/dtd/book.dtd">

<!-- The content of this document is licensed under the CC-BY-SA license -->
<!-- See http://creativecommons.org/licenses/by-sa/2.5 -->

<!-- $Header$ -->
<!-- English CVS version: 1.25 -->

<sections>

<version>9.0</version>
<date>2008-03-22</date>

<section>
<title>时区</title>
<body>

<p>
您首先需要选择您自己的时区，这样可以让系统知道它的位置在哪里。您可以在<path>/usr/share/zoneinfo</path>中找到您所在的时区，然后把它复制到<path>/etc/localtime</path>。请不要使用<path>/usr/share/zoneinfo/Etc/GMT*</path>下的时区，因为它们“名不副实”。例如，<path>GMT-8</path>事实上是GMT+8区。
</p>

<pre caption="设置时区信息">
# <i>ls /usr/share/zoneinfo</i>
<comment>（假设您要用GMT）</comment>
# <i>cp /usr/share/zoneinfo/GMT /etc/localtime</i>
</pre>

</body>
</section>
<section>
<title>安装源码</title>
<subsection>
<title>选择内核</title>
<body>

<p>
Linux内核是所有发行版的核心。它位于用户程序和系统硬件之间。Gentoo提供给我们几个可选的内核源码。完整的清单参见<uri link="/doc/en/gentoo-kernel.xml">Gentoo内核指南</uri>。
</p>

<p>
对于alpha架构的系统，可以使用<c>gentoo-sources</c>（默认的2.6内核源码）。
</p>

<pre caption="安装内核源码">
# <i>emerge gentoo-sources</i>
</pre>

<p>
当您查看<path>/usr/src</path>时，您将会看到一个叫做<path>linux</path>的符号链接指向您安装的内核源码。在我们这个例子中，安装的源码是<c>gentoo-sources-<keyval id="kernel-version"/></c>。您的版本可能有所不同，所以请您记住这一点。
</p>

<pre caption="查看内核源码符号链接">
# <i>ls -l /usr/src/linux</i>
lrwxrwxrwx    1 root     root           12 Oct 13 11:04 /usr/src/linux -&gt; linux-<keyval id="kernel-version"/>
</pre>

<p>
现在，我们开始配置和编译您的内核。您可以用<c>genkernel</c>来做这件事。这将会建立一个和安装光盘所用的内核相同的内核。我们将首先说明如何手动配置一个内核，因为这是优化您系统环境的最佳方法。
</p>

<p>
如果您希望手动配置您的内核，点击<uri link="#manual">默认：手动配置</uri>。如果您希望使用<c>genkernel</c>，您可以阅读<uri link="#genkernel">备选：使用genkernel</uri>。
</p>

</body>
</subsection>
</section>
<section id="manual">
<title>默认：手动配置</title>
<subsection>
<title>介绍</title>
<body>

<p>
手动配置内核经常被Linux使用者认为是最困难的步骤。事实并非如此——但是当您手动配置几次内核之后，您就不会再觉得它有多么难了。:)
</p>

<p>
然而，一件事情<e>是</e>真的：在手动配置内核之前，您必须了解您的系统。您可以安装pciutils（<c>emerge pciutils</c>），用其中的<c>lspci</c>来了解您需要的大部分信息。您现在可以在chroot的环境中运行<c>lspci</c>。您可以忽略任何<e>pcilib</e>的警告。（类似于pcilib: cannot open/sys/bus/pci/devices）。此外，您也可以在非chroot的环境执行<c>lspci</c>。结果相同。您还可以运行<c>lsmod</c>来查看安装光盘使用了哪些内核模块。（这也是个不错的提示，它可以教你该选择哪些模块）。
</p>

<p>
现在进入到您的内核目录并且执行<c>make menuconfig</c>。这将会启动一个基于ncureses的配置菜单。
</p>

<pre caption="开始menuconfig">
# <i>cd /usr/src/linux</i>
# <i>make menuconfig</i>
</pre>

<p>
您将会看到一些配置条目。首先我们将会列出一些您必须启用的选项（否则Gentoo将不能正常运行或者根本不能运行）。
</p>

</body>
</subsection>
<subsection>
<title>必须启用的选项</title>
<body>

<p>
首先进入<c>File Systems</c>并选择您使用的文件系统。请<e>不要</e>把它们编译成模块，否则您的Gentoo系统将不能挂载您的分区。同时您也要启用<c>Virtual memory</c>和<c>/proc file system</c>的支持。
</p>

<pre caption="选择需要的文件系统">
File systems ---&gt;
  Pseudo Filesystems ---&gt;
    [*] /proc file system support
    [*] Virtual memory file system support (former shm fs)

<comment>（选择下面所列出的您的系统所需要的一个或多个选项）</comment>
  &lt;*&gt; Reiserfs support
  &lt;*&gt; Ext3 journalling file system support
  &lt;*&gt; JFS filesystem support
  &lt;*&gt; Second extended fs support
  &lt;*&gt; XFS filesystem support
</pre>

<p>
如果您在使用PPPoE接入Interne或者您在使用拨号的调制解调器，您需要下面的选项：
</p>

<pre caption="选择PPPoE驱动">
Device Drivers ---&gt;
  Networking support ---&gt;
    &lt;*&gt; PPP (point-to-point protocol) support
    &lt;*&gt;   PPP support for async serial ports
    &lt;*&gt;   PPP support for sync tty ports
</pre>

<p>
两个压缩选项不会造成什么错误，不过它们不是必需的。<c>PPP over Ethernet</c>选项也不是必需的，只在使用<c>ppp</c>并被配置成是使用核心PPPoE时才会用到它。
</p>

<p>
如果您需要它，请不要忘记在内核中包含对您的网卡的支持。
</p>

<p>
以下选项也是推荐您启用的：
</p>

<pre caption="推荐的Alpha选项">
General setup ---&gt;
  &lt;*&gt; SRM environment through procfs
  &lt;*&gt; Configure uac policy via sysctl

Plug and Play configuration ---&gt;
  &lt;*&gt; Plug and Play support
  &lt;M&gt;   ISA Plug and Play support

SCSI support ---&gt;
  SCSI low-level drivers ---&gt;
    &lt;*&gt; SYM53C8XX Version 2 SCSI support (NEW)
    &lt;*&gt; Qlogic ISP SCSI support

Network device support ---&gt;
  Ethernet (10 or 100 Mbit) ---&gt;
    &lt;M&gt; DECchip Tulip (dc21x4x) PCI support
    &lt;M&gt; Generic DECchip &amp; DIGITAL EtherWORKS PCI/EISA
    &lt;M&gt; EtherExpressPro/100 support (eepro100)
    &lt;M&gt; EtherExpressPro/100 support (e100)
  Ethernet (1000 Mbit) ---&gt;
    &lt;M&gt; Alteon AceNIC
      [*] Omit support for old Tigon I
    &lt;M&gt; Broadcom Tigon3
  [*] FDDI driver support
  &lt;M&gt; Digital DEFEA and DEFPA
  &lt;*&gt; PPP support
    &lt;*&gt; PPP Deflate compression

Character devices ---&gt;
  [*] Support for console on serial port
  [*] Direct Rendering Manager

File systems ---&gt;
  &lt;*&gt; Kernel automounter version 4 support
  Network File Systems ---&gt;
    &lt;*&gt; NFS
      [*] NFSv3 client
      &lt;*&gt; NFS server
      [*] NFSv3 server
  Partition Types ---&gt;
    [*] Advanced partition selection
    [*] Alpha OSF partition support
  Native Language Support
    &lt;*&gt; NLS ISO 8859-1

Sound ---&gt;
  &lt;M&gt; Sound card support
    &lt;M&gt; OSS sound modules
      [*] Verbose initialisation
      [*] Persistent DMA buffers
      &lt;M&gt; 100% Sound Blaster compatibles
</pre>

<p>
当您完成了内核配置，点击<uri link="#compiling">编译与安装</uri>。
</p>

</body>
</subsection>
<subsection id="compiling">
<title>编译与安装</title>
<body>

<p>
既然现在您的内核已经配置成功了，那么就是时候编译并且安装它了。退出配置界面并且开启编译进程：
</p>

<pre caption="编译内核">
# <i>make &amp;&amp; make modules_install</i>
# <i>make boot</i>
</pre>

<p>
当内核编译完成，复制内核镜像到<path>/boot</path>。较新版本的内核会创建<path>vmlinux</path>而不是<path>vmlinux.gz</path>。您复制内核镜像的时候要记清楚了。
</p>

<pre caption="安装内核">
# <i>cp arch/alpha/boot/vmlinux.gz /boot/</i>
</pre>

<p>
现在请从<uri link="#kernel_modules">内核模块</uri>一节继续安装。
</p>

</body>
</subsection>
</section>
<section id="genkernel">
<title>备选：使用genkernel</title>
<body>

<p>
如果您在阅读这部分，那么您选择了使用<c>genkernel</c>脚本来配置您自己的内核。
</p>

<p>
现在您的内核源码树已经安装了，是时候用<c>genkernel</c>脚本自动编译您的内核了。<c>genkernel</c>是使用类似安装光盘中的内核配置来配置内核的。这表明当您用<c>genkernel</c>建立内核时，您的系统在启动时候将会如同安装光盘那样识别您所有的硬件。因为genkernel不需要手动配置内核，所以它对于那些不想自己编译特定内核的用户来说是一个理想的解决方案。
</p>

<p>
现在让我们来看看如何使用genkernel吧。首先，安装genkernel：
</p>

<pre caption="安装genkernel">
# <i>emerge genkernel</i>
</pre>

<p>
现在执行<c>genkernel all</c>编译您的内核源码。请注意，<c>genkernel</c>编译出的内核支持几乎所有硬件，编译需要一段很长的时间。
</p>

<p>
另外需要注意的是，如果您的启动分区没有使用ext2或者ext3文件系统，您必须使用<c>genkernel --menuconfig all</c>来手动配置您的内核，把您所使用的文件系统编译进内核（<e>不能</e>编译为模块！）。
</p>

<pre caption="运行genkernel">
# <i>genkernel all</i>
</pre>

<p>
一旦<c>genkernel</c>运行完成，一个包括全部模块和initrd的内核将被建立。在后面配置引导程序时我们将会用到这个内核和initrd。请记下内核和initrd的名字，因为您将在配置引导程序的时候用到他们。initrd将会在启动真正的系统前自动识别硬件（如同安装光盘一样）。
</p>

<pre caption="查看内核和initrd的名字">
# <i>ls /boot/kernel* /boot/initramfs-*</i>
</pre>

</body>
</section>
<section id="kernel_modules">
<title>内核模块</title>
<subsection>
<include href="hb-install-kernelmodules.xml"/>
</subsection>
</section>
</sections>

=== r0bertz/gentoo-cn/doc/zh_cn/handbook/2006.1/hb-install-gli-dialog.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet type="text/xsl" href="/xsl/guide.xsl" ?>
<!DOCTYPE sections SYSTEM "/dtd/book.dtd">
<!-- $Header: /var/cvsroot/gentoo/xml/htdocs/doc/en/handbook/2006.1/hb-install-gli-dialog.xml,v 1.2 2006/11/01 23:57:49 nightmorph Exp $ -->

<!--  The content of this document is licensed under the CC-BY-SA license -->
<!--  See http://creativecommons.org/licenses/by-sa/2.5 -->

<sections>

<version>2.1</version>
<date>2006-11-01</date>

<section>
<title>欢迎</title>
<subsection>
<title>在您开始之前</title>
<body>

<p>
启动Gentoo Linux 安装程序LiveCD后，默认会载入一个图形桌面。若不能启动图形桌面，
则会显示一个命令行提示符。运行安装程序，只需简单输入：
</p>

<pre caption="运行安装程序">
# <i>installer</i>
</pre>

<p>
当安装程序加载结束后，你会看到显示屏上欢迎的问候信息。它提供了一份友好的Gentoo安
装步骤的说明。请仔细阅读每一个选项。屏幕顶端有每一个安装步骤的详细帮助信息。我们
建议你在做出每个选择前，都参考一下帮助信息。请注意在安装过程中的任何时候您都可以
保存你的配置进度，以便在中止后随时继续之前的安装。请使用（你键盘上
的）<c>Tab</c>键选择屏幕上的菜单，使用<c>Enter</c>键来确认一个动作。
</p>

<p>
这里提供两种可用的安装方式。选择<c>Networkless</c>来开始Gentoo Linux的安装。
</p>

<note>
选择<c>networkless</c>方式会导致后面的一些配置选项不可用，直接忽略并进入下一步即
可。
</note>

</body>
</subsection>
</section>

<section>
<title>安装前的配置</title>
<subsection>
<title>可选：手动配置网络</title>
<body>

<p>
尽管我们安装时并不需要连接到Internet，但你可以手动设置将机器连入局域网，那样你就
可以从局域网中的另一台机来远程安装Gentoo。
</p>

<p>
如果您想通过SSH访问这台机器（以便进行远程安装），可以启动<c>sshd</c>，并设置一
个root密码。
</p>

</body>
</subsection>
<subsection>
<title>可选：加载额外的内核模块</title>
<body>

<p>
如果您需要加载更多的内核模块以支持您的硬件，请输入它们的名字，用空格分开。
</p>

</body>
</subsection>
</section>

<section>
<title>分区</title>
<subsection>
<title>预备磁盘</title>
<body>

<p>
为了在你的机器上安装Gentoo，你需要准备好磁盘。<e>Partitioning</e>画面将显示已
检测到的磁盘列表，您可以为每一个分区指定文件系统。选择<c>Clear partitions</c>将
会清除您磁盘上先前所有的分区，请谨慎使用！你也可以为某些分区重新指定大小。
</p>

<p>
如果您选择<c>Recommend layout</c>，安装程序将建立三个分区：<path>/boot:</path>
100MB,<path>/swap:</path>最多512MB，剩下的所有有效空间都给<path>/</path>根分区
使用。如果您的硬盘上未分区的空间大于4GB，使用“Recommend layout”将自动分区并且不
会破坏您原有分区上的任何数据。
</p>

<warn>
在使用任何分区工具来更改您的分区表前，您都应该先备份好您的系统，任何一点bug都可
能造成您数据的丢失。
</warn>

</body>
</subsection>
</section>

<section>
<title>网络磁盘挂载</title>
<subsection>
<title>可选：定义网络磁盘</title>
<body>

<p>
本节中您可以设置和挂载任何已经存在的网络磁盘，以便在安装过程中和安装后使用。目前只支持NFS。
</p>

</body>
</subsection>
</section>

<!-- removed per codeman's suggestion on IRC; selecting "Networkless at
beginning makes these options unavailable

<section>
<title>Stage Selection</title>
<subsection>
<title>Dynamic stage generation</title>
<body>

<p>
Since you are performing an installation <e>without</e> an internet connection,
you <e>must</e> select <c>3+GRP</c> from the stage options present. Then, on the next
screen, select <c>Create from 光盘</c>. Everything you need to build your system will
then be generated from the files on the LiveCD.
</p>

<warn>
Do <e>not</e> select any options other than those specified above when you are
installing without an internet connection.
</warn>

</body>
</subsection>
</section>

<section>
<title>Portage Tree</title>
<subsection>
<title>Obtaining a Portage tree</title>
<body>

<p>
You must choose <c>Snapshot</c> on this screen. The installer will automatically
install a Portage tree from the LiveCD once you select Snapshot; you do not
need to specify a snapshot URI.
</p>

</body>
</subsection>
</section>

-->

<section>
<title>make.conf</title>
<subsection>
<title>USE标记</title>
<body>

<p>
因为您正在进行GRP/无网络安装，所以不能在安装之前选择USE标记。不过，当您重启进入安装
完成的系统后，您就可以在<path>/etc/make.conf</path>中设置USE标记了。
</p>

</body>
</subsection>
<subsection>
<title>CFLAGS</title>
<body>

<p>
在CFLAGS这一节您可以选择你的处理器类型以及设定任何你想要的优化参数，比
如<c>-O2</c>和<c>-pipe</c>。
</p>

</body>
</subsection>
<subsection>
<title>FEATURES</title>
<body>

<p>
现在你可以设置将来想用的任何其他选项。请遍阅可用的<b>FEATURES</b>，然后作出选择。
</p>

</body>
</subsection>
</section>

<section>
<title>内核源代码</title>
<subsection>
<title>使用LiveCD的内核</title>
<body>

<p>
使用GRP/无网络方式安装，您必须使用LiveCD上提供的内核。这只是一个由Gentoo的内核
自动编译工具——<c>genkernel</c>编译的<c>gentoo-sources</c>内核，它可以在您开机的
时候自动检测并设置您的硬件。
</p>

</body>
</subsection>
</section>

<section>
<title>Bootloader</title>
<subsection>
<title>作出你的选择</title>
<body>

<p>
在这一节，您可以选择系统bootloader。然后选择你的启动设备，最后如果需要，也可以指定额外的启动选项。
</p>

</body>
</subsection>
</section>

<section>
<title>时区</title>
<subsection>
<title>选择你的时区</title>
<body>

<p>
从列表中选择跟你实际位置最近的地区。
</p>

</body>
</subsection>
</section>

<section>
<title>网络</title>
<subsection>
<title>添加网络设备</title>
<body>

<p>
在这一节，你可以配置检测到的各种各样的网络设备。仔细阅读可用的选项。
</p>

<p>
下一节你可以选择使用DHCP或手动配置IP地址。一旦网络设备正确配置好了，你就要为系
统设一个主机名。如果需要，您还可以指定一个域名以及任何必要的DNS服务器信息。
</p>

</body>
</subsection>
</section>

<section>
<title>额外的软件包</title>
<subsection>
<title>可选: 安装额外的软件包</title>
<body>

<p>
LiveCD已经包含了许多预编译包。如果您想安装的话，请勾上相应的确认框。
</p>

</body>
</subsection>
</section>

<section>
<title>开机时启动的服务</title>
<subsection>
<body>

<p>
在这一节您可以选择开机时要启动的一些服务。仔细阅读可用的选项和描述，然后选择您想要
的服务。举个例子，如果您已经选择安装<c>xorg-x11</c>，并想一开机就直接进入图形桌
面，那您就要从列表中选择“xdm”。
</p>

</body>
</subsection>
</section>

<section>
<title>其他设置</title>
<subsection>
<title>杂项</title>
<body>

<p>
现在您可以调整各种设定，包括键盘布局、图形化的显示管理器、默认编辑器，以及设定
您的系统时钟（UTC时间还是local时间）。
</p>

</body>
</subsection>
</section>

<section>
<title>用户</title>
<subsection>
<title>添加用户和组</title>
<body>

<p>
首先为系统管理员（<e>root</e>用户）设置root密码。
</p>

<p>
我们<e>强烈</e>建议你创建一个普通用户，作为平时使用。用root用户来完成所有工作非
常不安全，应当尽量避免！建立您的用户，设定密码，并加入到合适的组中。您也可以为
用户另外指定主目录，选择一个shell，以及添加有用的注释。
</p>

</body>
</subsection>
</section>

<section>
<title>回顾</title>
<subsection>
<title>完工</title>
<body>

<p>
请花点时间再次检查一下安装过程中的每一个步骤，确认您的系统设置正确。当您检查完
成之后，您就可以保存设定并退出，或者选择<c>Install</c>开始自动安装gentoo.
</p>

<p>
安装程序会在安装结束时提示你。你会回到命令提示符。之后要做的事就是重启系统，输入：
</p>

<pre caption="重新启动">
# <i>shutdown -r now</i>
</pre>

<p>
恭喜，您的系统现在已经安装好了。接下来请看<uri link="?part=1&amp;chap=5">下一步该
怎么走？</uri>一章以学习更多关于Gentoo的知识。
</p>

</body>
</subsection>
</section>
</sections>

<!--
Steps of the dialog:
(pre): type installer at the prompt to begin the dialog
1. Partitioning
(note: we absolutely must include partitioning info here; gli-dialog refers
users to the partitioning info in the gentoo handbook! note that the gtkfe
installer already has this partition info in its graphical help screens)

2. Network mounts
3. Stage Selection
4. kernel sources
5. bootloader
6. timezone
7. network interface selection/configuration (inc. dhcp/static-manual)
8. hostname/domainname/dns
9. Optional: install additional packages
10. set root password
11. add user, set passwords/groups
12. review
(post) finishes, drops to prompt: shutdown -r now
-->
